CREATE TABLE `book` (
	`id` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`author` VARCHAR(255) NULL DEFAULT NULL,
	`genre` VARCHAR(255) NULL DEFAULT NULL,
	`isbn` VARCHAR(255) NULL DEFAULT NULL,
	`published` INT(11) NOT NULL,
	`title` VARCHAR(255) NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
